export const AESTHETICS = {
  clean: {
    id: "clean",
    name: "The Clean Girl",
    tagline: "Effortlessly Elevated",
    description: "You are the embodiment of intentional living. You don't chase trends — you set the standard quietly and consistently. Your life is your canvas and you keep it clean, curated, and undeniably yours. People notice you without knowing exactly why. It's because everything about you is on purpose.",
    color: "#b8a898",
    accent: "#d4c4b0",
    icon: "◌",
    goals: [
      "Drink 64oz of water",
      "Skincare morning & night",
      "Move your body 30 min",
      "Prep tomorrow's outfit tonight",
      "No phone first 30 min of morning",
    ],
  },
  soft: {
    id: "soft",
    name: "The Soft Life Girl",
    tagline: "Luxury Is Her Love Language",
    description: "You have decided — with full conviction — that you deserve ease. Not laziness, but intentional softness. You protect your peace like it's your most valuable asset, because it is. You are learning that receiving is just as powerful as giving, and that a life that feels good is a life well lived.",
    color: "#c4a882",
    accent: "#e8d4b8",
    icon: "◯",
    goals: [
      "Morning ritual — no rushing",
      "One thing that brings you joy today",
      "Say no to something that drains you",
      "Nourish your body with a real meal",
      "Rest without guilt tonight",
    ],
  },
  corporate: {
    id: "corporate",
    name: "The Corporate Baddie",
    tagline: "Boardroom Ready, Always",
    description: "You move with precision and purpose. The corner office, the negotiation, the vision — you see it all clearly and you're building toward it every single day. You know that ambition and femininity are not opposites. You are proof that a woman can be powerful, polished, and completely herself all at once.",
    color: "#8a9aaa",
    accent: "#b0c4d4",
    icon: "◈",
    goals: [
      "Review your top 3 priorities",
      "One hour of deep, focused work",
      "Send that email you've been avoiding",
      "Learn something new in your field",
      "End your day with a clear desk",
    ],
  },
  wellness: {
    id: "wellness",
    name: "The Wellness Girl",
    tagline: "Whole in Body, Mind & Spirit",
    description: "You understand something most people are still learning — that your health is your wealth. You listen to your body, you protect your energy, and you know that how you feel on the inside shows up on the outside. You are not chasing perfection. You are choosing wholeness, one intentional day at a time.",
    color: "#8a9e88",
    accent: "#b4c8b0",
    icon: "✦",
    goals: [
      "Move your body — walk, stretch, sweat",
      "Meditate or breathe for 10 minutes",
      "Eat something that loves you back",
      "Get 7–8 hours of sleep",
      "Spend time in nature or sunlight",
    ],
  },
  luxury: {
    id: "luxury",
    name: "The Minimal Luxury Girl",
    tagline: "Less, But Only the Best",
    description: "You have mastered the art of less. You are not impressed by excess — you are moved by quality, craftsmanship, and intention. Your home, your wardrobe, your relationships — everything is curated. You know that true luxury is not about what you have, but about how deliberately you live. You are understated, and that is your power.",
    color: "#c9a84c",
    accent: "#e8c97a",
    icon: "◇",
    goals: [
      "Declutter one space in your home",
      "Invest in one quality thing today",
      "Choose depth over distraction",
      "Protect your time fiercely",
      "One moment of pure, undistracted pleasure",
    ],
  },
};

export const QUESTIONS = [
  {
    id: 1,
    question: "Your ideal Sunday morning looks like…",
    options: [
      { text: "Matcha, a clean kitchen, and a slow getting-ready routine", scores: { clean: 3, luxury: 2 } },
      { text: "Sleeping in, room service energy, zero obligations", scores: { soft: 3, luxury: 1 } },
      { text: "Up early, inbox checked, ahead of the week", scores: { corporate: 3, clean: 1 } },
      { text: "Yoga, journaling, farmers market", scores: { wellness: 3, soft: 1 } },
      { text: "A quiet home, a good book, intentional stillness", scores: { luxury: 3, soft: 2 } },
    ],
  },
  {
    id: 2,
    question: "Your bag is…",
    options: [
      { text: "Organized, minimal, only the essentials — but make it cute", scores: { clean: 3, luxury: 2 } },
      { text: "Whatever holds everything I need to be comfortable", scores: { soft: 3 } },
      { text: "A structured tote with my laptop, planner, and AirPods", scores: { corporate: 3, clean: 1 } },
      { text: "My reusable water bottle lives in it permanently", scores: { wellness: 3 } },
      { text: "One beautiful bag. Investment piece. No regrets.", scores: { luxury: 3, corporate: 1 } },
    ],
  },
  {
    id: 3,
    question: "When you think about your dream life, the first thing that comes to mind is…",
    options: [
      { text: "A life that looks and feels put-together effortlessly", scores: { clean: 3, luxury: 1 } },
      { text: "Ease. Warmth. Never having to rush again.", scores: { soft: 3, wellness: 1 } },
      { text: "Making it. The title, the income, the impact.", scores: { corporate: 3 } },
      { text: "Feeling genuinely good — in my body, mind, spirit", scores: { wellness: 3, soft: 1 } },
      { text: "A beautiful, quiet life with only what truly matters", scores: { luxury: 3, clean: 1 } },
    ],
  },
  {
    id: 4,
    question: "Your self-care looks like…",
    options: [
      { text: "Skincare, silk pillowcase, curated playlist, aesthetic bathroom", scores: { clean: 3, luxury: 1 } },
      { text: "A long bath, candles, doing absolutely nothing", scores: { soft: 3, luxury: 1 } },
      { text: "Efficient. A routine that keeps me sharp and ready.", scores: { corporate: 3, clean: 1 } },
      { text: "Holistic — supplements, movement, mindfulness, sleep", scores: { wellness: 3 } },
      { text: "Investing in one high-quality experience that restores me", scores: { luxury: 3, soft: 1 } },
    ],
  },
  {
    id: 5,
    question: "Your home aesthetic is…",
    options: [
      { text: "Bright, clean, neutral — everything has a place", scores: { clean: 3, luxury: 1 } },
      { text: "Cozy, layered, warm — a true sanctuary", scores: { soft: 3, wellness: 1 } },
      { text: "Sleek, functional, modern — designed for productivity", scores: { corporate: 3, luxury: 1 } },
      { text: "Natural textures, plants, calm energy everywhere", scores: { wellness: 3, soft: 1 } },
      { text: "Sparse, intentional, only beautiful things", scores: { luxury: 3, clean: 2 } },
    ],
  },
  {
    id: 6,
    question: "When you invest in yourself, it's usually…",
    options: [
      { text: "A new skincare routine or something that upgrades my look", scores: { clean: 3 } },
      { text: "An experience — a trip, a spa day, something that fills me up", scores: { soft: 3, luxury: 1 } },
      { text: "A course, a mentor, a skill that moves my career forward", scores: { corporate: 3 } },
      { text: "My health — a program, equipment, nutrition", scores: { wellness: 3 } },
      { text: "One timeless, quality thing I'll have forever", scores: { luxury: 3, clean: 1 } },
    ],
  },
  {
    id: 7,
    question: "The word that describes how you want to feel every day is…",
    options: [
      { text: "Polished", scores: { clean: 3, corporate: 1 } },
      { text: "Peaceful", scores: { soft: 3, wellness: 2 } },
      { text: "Powerful", scores: { corporate: 3, clean: 1 } },
      { text: "Balanced", scores: { wellness: 3, soft: 1 } },
      { text: "Refined", scores: { luxury: 3, clean: 1 } },
    ],
  },
  {
    id: 8,
    question: "Your relationship with ambition is…",
    options: [
      { text: "I want to build something beautiful and be recognized for it", scores: { clean: 2, corporate: 2 } },
      { text: "I want to thrive without grinding. Abundance, not hustle.", scores: { soft: 3, luxury: 1 } },
      { text: "I am deeply driven. Success is non-negotiable for me.", scores: { corporate: 3 } },
      { text: "I want to grow, but sustainably — aligned with my wellbeing", scores: { wellness: 3, soft: 1 } },
      { text: "I want a life so well-built I never have to prove anything", scores: { luxury: 3, corporate: 1 } },
    ],
  },
];

export const QUOTES = [
  "Soft is not weak. Intentional is powerful.",
  "She who shows up daily becomes unstoppable.",
  "Growth isn't loud. It's consistent.",
  "You don't need motivation. You need commitment.",
  "The woman you're becoming will thank you.",
  "Discipline is the highest form of self-love.",
  "She decided she was enough. Everything changed.",
  "A grown woman knows her worth and acts accordingly.",
];
